---
application:
  name: "jeevcallmusic"
  project: "music"
  organization: "QoveryCommunity"
  cpu: "8"
  ram: "32GB"
  storage:
  - name: "jeevcallmusic"
    size: "200"
    type: "fast_ssd"
    mount_point: "/mnt/"
routers:
- name: "main-jeevcallmusic"
  routes:
  - application_name: "jeevcallmusic"
    paths:
    - "/*"
