---
application:
  name: "jeevcallmusic"
  project: "music"
  organization: "QoveryCommunity"
  cpu: "8"
  ram: "16GB"
routers:
- name: "main-jeevcallmusic"
  routes:
  - application_name: "jeevcallmusic"
    paths:
    - "/*"
