---
application:
  name: "jeevcallmusic"
  project: "music"
  organization: "QoveryCommunity"
routers:
- name: "main-jeevcallmusic"
  routes:
  - application_name: "jeevcallmusic"
    paths:
    - "/*"
